### ISSUE TITLE
Mysterious cpanm Failures on Windows

### ISSUE THREAD

**Issue by theory** [shogo82148/actions-setup-perl#225]
Reference: https://github.com/theory/semver/runs/657320188?check_suite_focus=true

No useful error output that I can see, sadly.

**Comment by shogo82148** [comment]
https://help.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run#enabling-debug-logging
You can enable debug logging. Please try it if cpanm still doesn't work.

I close this issue because it looks that the recent builds succeeded.

**Comment by theory** [comment]
[Still failing](https://github.com/theory/semver/runs/681399970?check_suite_focus=true). Will try debugging.

**Comment by theory** [comment]
Ran with debugging, downloaded, found only this:

```
2020-05-16T19:17:14.4613983Z ##[group]Run cpanm --installdeps --with-recommends --notest -v .
2020-05-16T19:17:14.4614276Z [36;1mcpanm --installdeps --with-recommends --notest -v .[0m
2020-05-16T19:17:14.4661776Z shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
2020-05-16T19:17:14.4661985Z ##[endgroup]
2020-05-16T19:17:16.7963438Z ##[error]Process completed with exit code 1.
```

:-(

Note that I'm using the `-v` option on `cpanm` to make it verbose, but nothing appears in the output, sadly.

**Comment by shogo82148** [comment]
it's bad news :-(

I sometimes get `EXCEPTION_ACCESS_VIOLATION` while building the Perl Core modules.
It is fixed by disabling C compiler optimization, so I disabled the optimization in all versions as a workaround.

https://github.com/shogo82148/actions-setup-perl/pull/232
https://github.com/shogo82148/actions-setup-perl/releases/tag/v1.3.2

could you try it, please.

**Comment by theory** [comment]
[still not happy](https://github.com/theory/semver/runs/682842936?check_suite_focus=true). Seems fine with 5.14 and higher; it's 5.12 and lower that pukes.

**Comment by theory** [comment]
Any ideas, @shogo82148? Only seems to be a problem with 5.12, 5.10, and 5.8 on Windows.

**Comment by shogo82148** [comment]
I have no idea 😭 
but Strawberry Perl may resolve it https://github.com/shogo82148/actions-setup-perl/issues/235
I'll try it later.

**Comment by theory** [comment]
Oh, yeah, using the Strawberry binaries might indeed do the trick. Looking forward to trying it out!

**Comment by shogo82148** [comment]
http://strawberryperl.com/releases.html
Strawberry Perl doesn't provide 64-bit binary of Perl 5.12 or earlier 😢

**Comment by theory** [comment]
Oh, well crap!

**Comment by lskatz** [comment]
cpanm mysteriously does not install modules for me either.  For example: https://github.com/lskatz/endopep_peaks/runs/1161249764?check_suite_focus=true

**Comment by shogo82148** [comment]
It will be fixed by https://github.com/shogo82148/actions-setup-perl/pull/474, https://github.com/shogo82148/actions-setup-perl/pull/475, https://github.com/shogo82148/actions-setup-perl/pull/477, https://github.com/shogo82148/actions-setup-perl/pull/480, and https://github.com/shogo82148/actions-setup-perl/pull/481

**Comment by theory** [comment]
Tried turning tests for 5.8, 5.10, and 5.12 on Windows again in /theory/semver@8bfa9f8, but alas,[ it failed](https://github.com/theory/semver/actions/runs/393003809) with "Error: unable to get latest version". Are the binaries missing?
